raw_digit_dimensions: List[int] = [3,240, 320]
blank_ref_root: /home/rotem/dlopredict/src/datasets/ds_h5/digit_blank_closed_refs
n_markers: 14
past_window_steps: 1
max_time_delta: 0.13
model_params:
  use_spline: true
  pose_backbone:
    hidden_dim: 512
  image_backbone:
    model_type: vit_small
    fusion_layers:
    - 9
    - 10
    - 11
    - 12
    type: sparsh_vit
    multi_scale_fusion: true
    unfreeze_last_n_blocks: 2
    single_encoder: true
    fusion_method: learned_sum
    pretrained_weights_path: /home/rotem/dlopredict/src/sparsh/checkpoints/dino_vitsmall.ckpt
    backbone_lr_factor: 0.5
    upto_layer: 2
  latent_dim: 128
  use_sinusoidal_pos_encoding: true
use_global_decoder: false
use_lr_scheduler: true
lr_warmup_pct: 0.1
lr_div_factor: 10
lr_final_div_factor: 100
max_grad_norm: 0.5
chamfer_weight: 0.25
mse_weight: 1
w_nodes: 1
w_edges: 0.1
w_lengths: 0.5
w_kb: 0.01
with_att: true
use_diff_images: true
num_output_pts: 32
n_control_points: 32
use_blank_ref: true
normalize: true
normalize_inputs: true
only_pose: false
img_size_H: 320
img_size_W: 240
batch_size: 32
lr: 7.147008552233424e-05
weight_decay: 0.00010701368128884272
dropout: 0.1
epochs: 10
train_data_root: /home/rotem/dlopredict/src/datasets/ds/train
val_data_root: /home/rotem/dlopredict/src/datasets/ds/test
norm_stats_path: /home/rotem/dlopredict/src/simplepredict/configs/norm_stats.yaml
seed: 42
num_workers: 16
