
digit_pub_node:
  ros__parameters:
    rate: 200.0
    diff_with_ref: false
    resolution: "QVGA"
    fps: "high"  #  30, 60 for QVGA, 15, 30 for VGA
    intensity: 15


natnet_client_pub_node:
  ros__parameters:
    server_address: "132.66.210.173"
    client_address: "132.66.53.99"
    use_multicast: false
    rate: 500.0
    base_frame: base_link
    end_effector_frame: end_effector_link
    calibrate: True
    t_calib: [-0.037361, -0.581480, -0.032343]  # Calibration offset [0.220615, -0.545225, -0.026517]
    q_calib: [0.514472, 0.475635, 0.509970, 0.499020]  # Quaternion calibration offset 
    robot_base_rb_id: 1
    robot_ee_rb_id: 2
    fixed_ee_rb_id: 3
    natnet_world_frame: natnet_world
  

full_data_pub:
  ros__parameters:
    rate: 15
    num_markers: 12
    t_calib: [-0.037361, -0.581480, -0.032343]  # Calibration offset [0.220615, -0.545225, -0.026517]
    q_calib: [0.514472, 0.475635, 0.509970, 0.499020]  # Quaternion calibration offset 
